GET http://localhost:3002/users

###

GET http://localhost:3002/quizes

###

GET http://localhost:3002/completedQuizes

###


POST http://localhost:3002/quizes
Content-Type: application/json

{
    "questions": ["Question 1", "Question 2", "Question 3"],
    "title": "Quiz 1",
    "world": "Kanto",
    "badge": "Boulder Badge",
    "pointPerQuestion": 10
}
###

POST http://localhost:3002/login
Content-Type: application/json

{
    "email": "regTest1@gmail.com"
}


###

POST http://localhost:3002/users
Content-Type: application/json

{
    "username": "firstUserEver",
    "email": "one@gmail.com",
    "password": "123",
    "starter": "Bulbasaur"
}

###

POST http://localhost:3002/completedQuizes
Content-Type: application/json

{
    "score": 100,
    "badge": "Boulder Badge",
    "quizRef": "64fbe7e73aa997c2f91bd7ee",
    "world": "Kanto"
}


###

PATCH http://localhost:3002/users/64fa84c09d1f791b46ee5811
Content-Type: application/json

{
    "newQuiz": {
        "score": 100,
        "badge": "Boulder Badge",
        "world": "Kanto",
        "quizRef": "64fbe7e73aa997c2f91bd7ee",
        "_id": "64fe1b83073b3d6e440cd345",
        "__v": 0
    }
}

###

PATCH http://localhost:3002/users/64fa84c09d1f791b46ee5811
Content-Type: application/json

{
    "favorites": [ 1, 2, 3]
}



###

DELETE http://localhost:3002/users/65024e112e21c396c71025ea