GET http://localhost:3002/users

###

GET http://localhost:3002/users/65222ef1380098b96f26fc7d

###

GET http://localhost:3002/quizes

###

GET http://localhost:3002/completedQuizes

###



DELETE http://localhost:3002/quizes/6519e975686e8a2214fb87c3

###

POST http://localhost:3002/quizes
Content-Type: application/json

{
     "questions": [
                {
                    "question": "Name that pokemon",
                    "img": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/111.png",
                    "answers": [
                        {
                            "name": "Dugtrio",
                            "isCorrect": false
                        },
                        {
                            "name": "Nidoking",
                            "isCorrect": false
                        },
                        {
                            "name": "Nidoqueen",
                            "isCorrect": false
                        },
                        {
                            "name": "Ryhorn",
                            "isCorrect": true
                        }
                    ]
                },
                {
                    "question": "Name that pokemon",
                    "img": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/34.png",
                    "answers": [
                        {
                            "name": "Nidoking",
                            "isCorrect": true
                        },
                        {
                            "name": "Nidoqueen",
                            "isCorrect": false
                        },
                        {
                            "name": "Dugtrio",
                            "isCorrect": false
                        },
                        {
                            "name": "Ryhorn",
                            "isCorrect": false
                        }
                    ]
                },
                {
                    "question": "Name that pokemon",
                    "img": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/31.png",
                    "answers": [
                        {
                            "name": "Nidoqueen",
                            "isCorrect": true
                        },
                        {
                            "name": "Nidoking",
                            "isCorrect": false
                        },
                        {
                            "name": "Dugtrio",
                            "isCorrect": false
                        },
                        {
                            "name": "Ryhorn",
                            "isCorrect": false
                        }
                    ]
                },
                {
                    "question": "Name that pokemon",
                    "img": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/51.png",
                    "answers": [
                        {
                            "name": "Nidoking",
                            "isCorrect": false
                        },
                        {
                            "name": "Dugtrio",
                            "isCorrect": true
                        },
                        {
                            "name": "Ryhorn",
                            "isCorrect": false
                        },
                        {
                            "name": "Nidoqueen",
                            "isCorrect": false
                        }
                    ]
                },
                {
                    "question": "Name that pokemon",
                    "img": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/112.png",
                    "answers": [
                        {
                            "name": "Nidoking",
                            "isCorrect": false
                        },
                        {
                            "name": "Ryhorn",
                            "isCorrect": false
                        },
                        {
                            "name": "Rydon",
                            "isCorrect": true
                        },
                        {
                            "name": "Nidoqueen",
                            "isCorrect": false
                        }
                    ]
                }
            ],
            "title": "ViridianCity Gym",
            "world": "Kanto",
            "badge": "Earth Badge",
            "leader": "Giovanni",
            "pointsPerQuestion": 30
}
###

POST http://localhost:3002/login
Content-Type: application/json

{
    "email": "regTest1@gmail.com"
}


###

POST http://localhost:3002/users
Content-Type: application/json

{
    "username": "firstUserEver",
    "email": "one@gmail.com",
    "password": "123",
    "starter": "Bulbasaur"
}

###

POST http://localhost:3002/completedQuizes
Content-Type: application/json

{
    "score": 100,
    "badge": "Boulder Badge",
    "quizRef": "64fbe7e73aa997c2f91bd7ee",
    "world": "Kanto"
}


###

PATCH http://localhost:3002/users/64fa84c09d1f791b46ee5811
Content-Type: application/json

{
    "newQuiz": {
        "score": 100,
        "badge": "Boulder Badge",
        "world": "Kanto",
        "quizRef": "64fbe7e73aa997c2f91bd7ee",
        "_id": "64fe1b83073b3d6e440cd345",
        "__v": 0
    }
}

###

PATCH http://localhost:3002/users/64fa84c09d1f791b46ee5811
Content-Type: application/json

{
    "favorites": [ 1, 2, 3]
}



###

DELETE http://localhost:3002/users/65024e112e21c396c71025ea